INSERT INTO PERSON (ID, AGE, NAME) VALUES (100, 25, 'Pedro');
INSERT INTO PERSON (ID, AGE, NAME) VALUES (101, 26, 'Juan');
INSERT INTO PERSON (ID, AGE, NAME) VALUES (102, 22, 'Maria');
INSERT INTO PERSON (ID, AGE, NAME) VALUES (103, 25, 'Ana');
INSERT INTO PERSON (ID, AGE, NAME) VALUES (104, 29, 'Manuel');
